listener 8883
protocol mqtt

cafile D:/esp32-dashboard/certs/ca.crt
certfile D:/esp32-dashboard/certs/broker.crt
keyfile D:/esp32-dashboard/certs/broker.key
crlfile D:/esp32-dashboard/certs/crl.pem

tls_version tlsv1.2
require_certificate true
use_identity_as_username true

allow_anonymous false
acl_file D:/esp32-dashboard/mosquitto/acl.conf
